include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    always_declare_return_types: true
    close_sinks: true
    cancel_subscriptions: true
    require_trailing_commas: true
    empty_catches: false
    prefer_single_quotes: true
    unnecessary_await_in_return: true
    prefer_final_in_for_each: true
    prefer_final_locals: true